# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JsonPostRequest(BaseModel):
    action_id: Optional[int] = Field(
        None,
        description="Action that is being completed. This will validate that the action is still\nvalid before completed it. The same action can never be successfully passed twice to this endpoint.\nThe action must have a type of 'integration'.\n",
    )
    task_id: Optional[int] = Field(
        None,
        description="Task that is being completed. This will validate that the task is still\nvalid before completed it. The same action can never be successfully passed twice to this endpoint.\nThe task must have a type of 'integration'.\n",
    )
