# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class JsonPostRequest(BaseModel):
    account_tier_id: Optional[int] = Field(
        None, description='ID of the Account Tier for this Account'
    )
    city: Optional[str] = Field(None, description='City')
    company_stage_id: Optional[int] = Field(
        None, description='ID of the CompanyStage assigned to this Account'
    )
    company_type: Optional[str] = Field(
        None, description="Type of the Account's company"
    )
    conversational_name: Optional[str] = Field(
        None, description='Conversational name of the Account'
    )
    country: Optional[str] = Field(None, description='Country')
    crm_id: Optional[str] = Field(
        None,
        description='Requires Salesforce.\n\nID of the person in your external CRM. You must provide a crm_id_type if this is included.\n\nValidations will be applied to the crm_id depending on the crm_id_type. A "salesforce" ID must be exactly 18 characters. A "salesforce" ID must be either an Account (001) object. The type will be validated using the 18 character ID.\n\nThis field can only be used if your application or API key has the "account:set_crm_id" scope.\n\n',
    )
    crm_id_type: Optional[str] = Field(
        None,
        description='The CRM that the provided crm_id is for. Must be one of: salesforce',
    )
    custom_fields: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="Custom fields are defined by the user's team. Only fields with values are presented in the API.",
    )
    description: Optional[str] = Field(None, description='Description')
    do_not_contact: Optional[bool] = Field(
        None,
        description='Whether this company can not be contacted. Values are either true or false. Setting this to true will remove all associated people from all active communications',
    )
    domain: str = Field(..., description='Website domain, not a fully qualified URI')
    founded: Optional[str] = Field(None, description='Date or year of founding')
    id: Optional[int] = Field(
        None,
        description="ID of the account to update. Used if the upsert_key=id. When id and another upsert_key are provided,\nthe request will fail if the upsert record id and id parameter don't match.\n",
    )
    industry: Optional[str] = Field(None, description='Industry')
    linkedin_url: Optional[str] = Field(None, description='Full LinkedIn url')
    locale: Optional[str] = Field(None, description='Time locale')
    name: str = Field(..., description='Account Full Name')
    owner_id: Optional[int] = Field(
        None, description='ID of the User that owns this Account'
    )
    phone: Optional[str] = Field(None, description='Phone number without formatting')
    postal_code: Optional[str] = Field(None, description='Postal code')
    revenue_range: Optional[str] = Field(None, description='Estimated revenue range')
    size: Optional[str] = Field(
        None, description='Estimated number of people in employment'
    )
    state: Optional[str] = Field(None, description='State')
    street: Optional[str] = Field(None, description='Street name and number')
    tags: Optional[List[str]] = Field(
        None, description='All tags applied to this Account'
    )
    twitter_handle: Optional[str] = Field(None, description='Twitter handle, with @')
    upsert_key: Optional[str] = Field(
        None,
        description='Name of the parameter to upsert on. The field must be provided in the input parameters, or the request will fail.\nThe request will also fail if there are multiple records matched by the upsert field.\n\nIf upsert_key is not provided, this endpoint will not update an existing record.\n\nValid options are: id, crm_id, domain. If crm_id is provided, then a valid crm_id_type must be provided, as documented\nfor the account create and update endpoints.\n',
    )
    website: Optional[str] = Field(None, description='Website')
