# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class JsonPostRequest(BaseModel):
    cadence_content: Optional[Dict[str, Any]] = Field(
        None, description='Import data for cadence'
    )
    settings: Optional[Dict[str, Any]] = Field(
        None, description='Settings for a cadence'
    )
    sharing_settings: Optional[Dict[str, Any]] = Field(
        None, description='The shared settings for a cadence'
    )
