# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, RootModel

from . import CustomField


class JsonGetResponse(RootModel[List[CustomField]]):
    root: List[CustomField]


class JsonPostRequest(BaseModel):
    field_type: Optional[str] = Field(
        None,
        description='The field type of the custom field. Value must be one of: person, company, opportunity',
    )
    name: str = Field(..., description='The name of the custom field')
