# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JsonPutRequest(BaseModel):
    field_type: Optional[str] = Field(
        None,
        description='The field type of the custom field. Value must be one of: person, company, opportunity',
    )
    name: Optional[str] = Field(None, description='The name of the custom field')
