# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class JsonPostRequest(BaseModel):
    mailbox: str = Field(..., description='Email address of mailbox email was sent to')
    raw: str = Field(..., description='Base64 encoded MIME email content')
