# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JsonPutRequest(BaseModel):
    name: Optional[str] = Field(
        None, description='Name, recommended to be easily identifiable to a user'
    )
    user_id: Optional[int] = Field(
        None, description='ID of the User that owns this Import'
    )
