# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JsonPutRequest(BaseModel):
    event_id: Optional[str] = Field(
        None, description='Meeting ID from the calendar provider'
    )
    i_cal_uid: Optional[str] = Field(
        None, description='Meeting unique identifier (iCalUID)'
    )
    no_show: Optional[bool] = Field(
        None, description='Whether the meeting is a No Show meeting'
    )
    status: Optional[str] = Field(
        None,
        description='Status of the meeting creation progress. Possible values are: pending, booked, failed, retry',
    )
