# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import List

from pydantic import RootModel

from . import Meeting


class JsonGetResponse(RootModel[List[Meeting]]):
    root: List[Meeting]
