# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, RootModel

from . import Note


class JsonGetResponse(RootModel[List[Note]]):
    root: List[Note]


class JsonPostRequest(BaseModel):
    associated_with_id: int = Field(
        ..., description='ID of the item with which the note is associated'
    )
    associated_with_type: str = Field(
        ...,
        description='Case insensitive type of item with which the note is associated.  Value must be one of: person, account',
    )
    call_id: Optional[int] = Field(
        None,
        description='ID of the call with which the note is associated. The call cannot already have a note',
    )
    content: str = Field(..., description='The content of the note')
    skip_crm_sync: Optional[bool] = Field(
        None,
        description='Boolean indicating if the CRM sync should be skipped.  No syncing will occur if true',
    )
    subject: Optional[str] = Field(
        None, description="The subject of the note's crm activity, defaults to 'Note'"
    )
    user_guid: Optional[str] = Field(
        None,
        description='The user to create the note for. Only team admins may create notes on behalf of other users. Defaults to the requesting user',
    )
