# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JsonPutRequest(BaseModel):
    call_id: Optional[int] = Field(
        None,
        description='ID of the call with which the note is associated. The call cannot already have a note. If the note is associated to a call already, it will become associated to the requested call',
    )
    content: str = Field(..., description='The content of the note')
