# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JsonPostRequest(BaseModel):
    action_id: Optional[int] = Field(
        None,
        description='Action that is being marked ongoing. This will validate that the action is still\nvalid before modifying it. Ongoing actions can not be marked ongoing.\n',
    )
