# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JsonPutRequest(BaseModel):
    error_message: Optional[str] = Field(
        None, description='The error message indicating why the email failed to send'
    )
    message_id: str = Field(
        ..., description='The message id of the email that was sent'
    )
    sent_at: Optional[str] = Field(
        None, description='The time that the email was actually sent in iso8601 format'
    )
    status: str = Field(
        ...,
        description="Delivery status of the email.  Valid statuses are 'sent' and 'failed'",
    )
