# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class JsonPutRequest(BaseModel):
    name: str = Field(..., description='The name of the stage.')
