# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class JsonPostRequest(BaseModel):
    account_id: Optional[int] = Field(
        None, description='ID of the Account to link this person to'
    )
    city: Optional[str] = Field(None, description='City')
    contact_restrictions: Optional[List[str]] = Field(
        None,
        description='Specific methods of communication to prevent for this person. This will prevent individual execution of these communication types as well as automatically skip cadence steps of this communication type for this person in SalesLoft. Values currently accepted: call, email, message',
    )
    country: Optional[str] = Field(None, description='Country')
    crm_id: Optional[str] = Field(
        None,
        description='Requires Salesforce.\n\nID of the person in your external CRM. You must provide a crm_id_type if this is included.\n\nValidations will be applied to the crm_id depending on the crm_id_type. A "salesforce" ID must be exactly 18 characters. A "salesforce" ID must be either a Lead (00Q) or Contact (003) object. The type will be validated using the 18 character ID.\n\nThis field can only be used if your application or API key has the "person:set_crm_id" scope.\n\n',
    )
    crm_id_type: Optional[str] = Field(
        None,
        description='The CRM that the provided crm_id is for. Must be one of: salesforce',
    )
    custom_fields: Optional[Dict[str, Any]] = Field(
        None,
        description="Custom fields are defined by the user's team. Only fields with values are presented in the API.",
    )
    do_not_contact: Optional[bool] = Field(
        None,
        description='Whether or not this person has opted out of all communication. Setting this value to true prevents this person from being called, emailed, or added to a cadence in SalesLoft. If this person is currently in a cadence, they will be removed.',
    )
    email_address: Optional[str] = Field(None, description='Email address')
    first_name: Optional[str] = Field(None, description='First name')
    home_phone: Optional[str] = Field(None, description='Home phone without formatting')
    id: Optional[int] = Field(
        None,
        description="ID of the person to update. Used if the upsert_key=id. When id and another upsert_key are provided,\nthe request will fail if the upsert record id and id parameter don't match.\n",
    )
    import_id: Optional[int] = Field(
        None,
        description='ID of the Import this person is a part of. A person can be part of multiple imports, but this ID will always be the most recent Import',
    )
    job_seniority: Optional[str] = Field(
        None,
        description='The Job Seniority of a Person, must be one of director, executive, individual_contributor, manager, vice_president, unknown',
    )
    last_name: Optional[str] = Field(None, description='Last name')
    linkedin_url: Optional[str] = Field(None, description='Linkedin URL')
    locale: Optional[str] = Field(None, description='Time locale of the person')
    mobile_phone: Optional[str] = Field(
        None, description='Mobile phone without formatting'
    )
    owner_id: Optional[int] = Field(
        None, description='ID of the User that owns this person'
    )
    person_company_industry: Optional[str] = Field(
        None,
        description='Company industry. This property is specific to this person, unrelated to the company object. Updating the company object associated with this person is recommended',
    )
    person_company_name: Optional[str] = Field(
        None,
        description='Company name. This property is specific to this person, unrelated to the company object. Updating the company object associated with this person is recommended',
    )
    person_company_website: Optional[str] = Field(
        None,
        description='Company website. This property is specific to this person, unrelated to the company object. Updating the company object associated with this person is recommended',
    )
    person_stage_id: Optional[int] = Field(
        None, description='ID of the PersonStage of this person'
    )
    personal_email_address: Optional[str] = Field(
        None, description='Personal email address'
    )
    personal_website: Optional[str] = Field(
        None, description='The website of this person'
    )
    phone: Optional[str] = Field(None, description='Phone without formatting')
    phone_extension: Optional[str] = Field(
        None, description='Phone extension without formatting'
    )
    secondary_email_address: Optional[str] = Field(
        None, description='Alternate email address'
    )
    state: Optional[str] = Field(None, description='State')
    tags: Optional[List[str]] = Field(
        None, description='All tags applied to this person'
    )
    title: Optional[str] = Field(None, description='Job title')
    twitter_handle: Optional[str] = Field(
        None, description='The twitter handle of this person'
    )
    upsert_key: Optional[str] = Field(
        None,
        description='Name of the parameter to upsert on. The field must be provided in the input parameters, or the request will fail.\nThe request will also fail if there are multiple records matched by the upsert field. This can occur if intentional duplicates\nby email address is enabled.\n\nIf upsert_key is not provided, this endpoint will not update an existing record.\n\nValid options are: id, crm_id, email_address. If crm_id is provided, then a valid crm_id_type must be provided, as documented\nfor the person create and update endpoints.\n',
    )
    work_city: Optional[str] = Field(None, description='Work location - city')
    work_country: Optional[str] = Field(None, description='Work location - country')
    work_state: Optional[str] = Field(None, description='Work location - state')
