# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field, RootModel

from . import PersonStage


class JsonGetResponse(RootModel[List[PersonStage]]):
    root: List[PersonStage]


class JsonPostRequest(BaseModel):
    name: str = Field(..., description='The name of the new stage')
