# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JsonPutRequest(BaseModel):
    is_default: Optional[bool] = Field(
        None, description='Whether the saved list view is the default'
    )
    name: Optional[str] = Field(None, description='The name of the saved list view')
    view_params: Optional[str] = Field(
        None, description='JSON object of list view parameters'
    )
