# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, RootModel

from . import SavedListView


class JsonGetResponse(RootModel[List[SavedListView]]):
    root: List[SavedListView]


class JsonPostRequest(BaseModel):
    is_default: Optional[bool] = Field(
        None, description='Whether the saved list view is the default'
    )
    name: str = Field(..., description='The name of the saved list view')
    view: str = Field(
        ...,
        description='The type of objects in the saved list view.  Value must be one of: people, companies, or recordings',
    )
    view_params: Optional[str] = Field(
        None, description='JSON object of list view parameters'
    )
