# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:09:08+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class JsonPutRequest(BaseModel):
    current_state: Optional[str] = Field(
        None, description='Current state of the task, valid options are: completed'
    )
    description: Optional[str] = Field(
        None,
        description='A description of the task recorded for person at completion time',
    )
    due_date: Optional[str] = Field(
        None, description='Date of when the Task is due, ISO-8601 date format required'
    )
    is_logged: Optional[bool] = Field(
        None, description='A flag to indicate that the task should only be logged'
    )
    remind_at: Optional[str] = Field(
        None,
        description='Datetime of when the user will be reminded of the task, ISO-8601 datetime format required',
    )
    subject: Optional[str] = Field(None, description='Subject line of the task')
